controllers/UserController.php
<?php

namespace app\controllers;

use app\models\db\Phone;
use app\models\db\User;
use app\models\forms\UserForm;
use app\services\UserService;
use app\services\PhoneService;
use yii\filters\AccessControl;
use yii\web\Controller;


class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['info', 'update'],
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],
                ],
            ],
        ];
    }

    public function actionInfo()
    {
        /** @var User $model */
        $user = \Yii::$app->user->identity;
        return $this->render('info', ['user' => $user]);
    }

    /**
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate()
    {
        $userId = \Yii::$app->user->getId();
        $form = UserService::createUserFormById($userId);
        $form->scenario = UserForm::SCENARIO_UPDATE;

        if ($form->load(\Yii::$app->request->post()) && $form->validate()) {
            if ($id = UserService::createFromUserForm($form)) {
                $phones = \Yii::$app->request->post('Phone');
                if (!empty($phones)) {
                    $phonesDto = PhoneService::createDtoFromPhonesAndUserId($phones, $userId);
                    PhoneService::updateUserPhones($phonesDto);
                }

                return $this->redirect(['info']);
            }
        }

        $phones = Phone::findAll(['user_id' => $userId]);
        if (empty($phones)) {
            $phones[] = new Phone();
        }
        return $this->render('update', [
            'model' => $form,
            'phones' => $phones,
        ]);
    }
}

views/user/info.php
<?php

use app\models\db\User;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $user app\models\db\User */
/* @var $startDate string */
/* @var $meterList array */
/* @var $railwayList array */

$this->title = 'Пользователь: ' . $user->xcode;
$this->params['breadcrumbs'][] = 'Инфо';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $user,
        'attributes' => array_merge([
            'xcode',
            'title',
            'email',
            'egrpo',
            'position1_full_name',
            'position2_full_name',
            [
                'attribute'  => 'signatory',
                'value'  => function ($model) {
                    /** @var User $model */

                    return User::getSignatoryList()[$model->signatory];
                },
            ],
            'created_at:datetime',
            'updated_at:datetime',
            'contract_number',
            'contract_conclusion_date:date',
            [
                'label' => 'Телефоны',
                'format' => 'raw',
                'value' => function ($model) {
                    /** @var User $model */

                    $phones = $model->phones;
                    $response = '';

                    foreach ($phones as $phone) {
                        $response .= $phone->comment . ' ' . $phone->number . '<br>';
                    }

                    return $response;
                }
            ],

        ], $user->is_railway ?
            [
                [
                    'label' => 'Ж/д',
                    'value' => function ($model) {
                        /** @var User $model */

                        $titles = ArrayHelper::getColumn($model->railways, 'title');
                        $response = implode(',', $titles);

                        return $response;
                    }
                ]
            ] : []),
    ]) ?>

    <?= Html::a('Редактировать', Url::to(['user/update']), ['class' => 'btn btn-success']) ?>

</div>

views/user/update.php
<?php

use app\assets\UserDynamicPhoneAsset;
use app\models\db\User;
use app\modules\admin\models\forms\UserForm;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\User */
/* @var $model UserForm */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Редактирование пользователя: ' . $model->xcode;
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>


    <div class="user-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'title') ?>

        <?= $form->field($model, 'email') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'egrpo')->textInput() ?>

        <div class="panel panel-default">
            <div class="panel-heading"><h4><i class="glyphicon glyphicon-pencil"></i> Ответственные лица</h4></div>
            <div class="panel-body">
                <div class="container-items">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <?= $form->field($model, 'position1_full_name')->textInput() ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <?= $form->field($model, 'position2_full_name')->textInput() ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <?= $form->field($model, 'signatory')->dropDownList(User::getSignatoryList()) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><h4><i class="glyphicon glyphicon-envelope"></i> Телефоны</h4></div>
            <div class="panel-body">
                <div class="container-items">
                    <?php foreach ($phones as $i => $phone): ?>
                        <div class="phone-item panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title pull-left">Телефон</h3>
                                <div class="pull-right">
                                    <button type="button" class="add-phone btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                                    <button type="button" class="remove-phone btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <?= $form->field($phone, "[{$i}]number")->textInput(['maxlength' => true]) ?>
                                    </div>
                                    <div class="col-sm-6">
                                        <?= $form->field($phone, "[{$i}]comment")->textInput(['maxlength' => true]) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
    <?php UserDynamicPhoneAsset::register($this) ?>
</div>