modules/admin/controllers/OrderController.php
<?php

namespace app\modules\admin\controllers;

use app\dto\date\DateDto;
use app\models\db\Meter;
use app\models\db\Order;
use app\models\db\Provider;
use app\models\db\Railway;
use app\models\db\User;
use app\modules\admin\models\searches\OrderSearch;
use app\services\OrderService;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_ADMINISTRATOR],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionListOrdersByProvider($providerId)
    {
        $query = Order::find()
            ->leftJoin(Meter::tableName(), 'meter_id=meter.id')
            ->where(['meter.provider_id' => $providerId]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $provider = Provider::findOne($providerId);

        return $this->render('list_orders_by_provider', ['dataProvider' => $dataProvider, 'provider' => $provider]);
    }

    public function actionListOrdersByRailway($railwayId)
    {
        $query = Order::find()->where(['railway_id' => $railwayId]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $railway = Railway::findOne($railwayId);

        return $this->render('list_orders_by_railway', ['dataProvider' => $dataProvider, 'railway' => $railway]);
    }

    public function actionPrint()
    {
        $dateFrom = Yii::$app->request->post('date_from');
        $dateTo = Yii::$app->request->post('date_to');
        $meterId = Yii::$app->request->post('meter_id');

        if (strlen($dateFrom) == 7) {
            $dateFrom = $dateFrom . '-01';
            $daysInMonth = date('t', strtotime($dateTo . '-01'));
            $dateTo = $dateTo . '-' . $daysInMonth;
        }

        $data = OrderService::getUserXlsData($dateFrom, $dateTo, $meterId);

        $spreadsheet = new Spreadsheet();
        try {
            $sheet = $spreadsheet->getActiveSheet();

            $sheet->setCellValue('A' . 1, 'Дата');
            $sheet->setCellValue('B' . 1, 'Номинация, тыс. м3');
            $sheet->setCellValue('C' . 1, 'Реноминация, тыс. м3');
            $sheet->setCellValue('D' . 1, 'z - код');

            $rowNumber = 2;
            if ($data->rows) {
                foreach ($data->rows as $rowDto) {
                    $sheet->setCellValue('A' . $rowNumber, $rowDto->date);
                    $sheet->setCellValue('B' . $rowNumber, $rowDto->nomination);
                    $sheet->setCellValue('C' . $rowNumber, $rowDto->renomination);
                    $sheet->setCellValue('D' . $rowNumber, $rowDto->zcode);

                    $rowNumber++;
                }
            }

            $filename = $dateFrom . '-' . $dateTo . '.xls';
            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="' . $filename . '"');
            header('Cache-Control: max-age=0');

            $writer = new Xls($spreadsheet);
            $writer->save('php://output');
        } catch (Exception $e) {
            Yii::error($e->getMessage());
        }
    }

    public function actionCurrentMonth()
    {
        $meterId = Yii::$app->request->get('meter_id');

        $this->layout = 'withoutBorder';

        $orders = Order::find()
            ->where(new Expression('MONTH(date) = MONTH(CURRENT_DATE()) AND YEAR(date) = YEAR(CURRENT_DATE())'))
            ->andWhere(['meter_id' => $meterId])
            ->orderBy('date')
            ->all();

        $nominationSum = 0;
        $renominationSum = 0;
        $ordersByDay = [];

        $days = date('t');
        foreach (range(1, $days) as $day) {
            $ordersByDay[$day] = date('Y-m-') . $day;
        }

        foreach ($orders as $order) {
            $nominationSum += $order->nomination;
            $renominationSum += (double)$order->renomination ?: $order->nomination;
            $ordersByDay[$order->getDay()] = $order;
        }

        $meter = Meter::findOne($meterId);
        if (Yii::$app->request->post('print')) {
            $sum = Yii::$app->request->post('nomination') ? $nominationSum : $renominationSum;
            foreach (range(1, date('t')) as $day) {
                $ordersByDay[$day] = 0;
            }
            foreach ($orders as $order) {
                $ordersByDay[$order->getDay()] = Yii::$app->request->post('nomination') ? $order->nomination ?: 0 : ((double)$order->renomination ?: $order->nomination ?: 0);
            }

            $startDate = "1." . date('m') . "." . date('Y');
            $endDate = $days . "." . date('m') . "." . date('Y');

            return $this->renderPartial('print-table',
                [
                    'dataByMonths' => [
                        'days'       => range(1, $days),
                        'meter'      => $meter,
                        'sum'        => $sum,
                        'orderByDay' => $ordersByDay,
                        'endDay'     => $days,
                        'month'      => date('m'),
                        'year'       => date('Y'),
                    ],
                    'endDate' => $endDate,
                    'startDate' => $startDate,
                    'days' => $days,
                    'meter' => $meter,
                ]
            );
        }

        return $this->render('table', [
            'meter'           => $meter,
            'date'            => date('m.Y'),
            'days'            => range(1, date('t')),
            'nominationSum'   => $nominationSum,
            'renominationSum' => $renominationSum,
            'orders'          => $ordersByDay,
        ]);
    }

    public function actionNextMonth()
    {
        $this->layout = 'withoutBorder';

        $meterId = Yii::$app->request->get('meter_id');
        /** @var User $user */

        $year = date('Y');
        $month = (string)date('m');
        if ($month == 12) {
            $month = '01';
            $year += 1;
        } else {
            $month += 1;
        }

        /** @var Order[] $orders */
        $orders = Order::find()
            ->where(new Expression('CAST(MONTH(date) AS UNSIGNED) = ' . $month . ' AND YEAR(date) = ' . $year))
            ->andWhere(['meter_id' => $meterId])
            ->orderBy('date')
            ->all();

        $nominationSum = 0;
        $renominationSum = 0;
        $ordersByDay = [];

        $days = date('t', strtotime("$year-$month-01"));
        foreach (range(1, $days) as $day) {
            $ordersByDay[$day] = "$year-$month-" . $day;
        }

        foreach ($orders as $order) {
            $nominationSum += $order->nomination;
            $renominationSum += (double)$order->renomination ?: $order->nomination;
            $ordersByDay[$order->getDay()] = $order;
        }

        $meter = Meter::findOne($meterId);
        if (Yii::$app->request->post('print')) {
            $sum = Yii::$app->request->post('nomination') ? $nominationSum : $renominationSum;
            foreach (range(1, $days) as $day) {
                $ordersByDay[$day] = 0;
            }

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\Meter;
use app\models\db\User;
use app\models\forms\UserForm;
use app\modules\admin\models\searches\UserSearch;
use app\services\UserService;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_ADMINISTRATOR],
                    ],
                ],
            ],
        ];
    }


    public function actionInfo()
    {
        /** @var User $model */
        $user = \Yii::$app->user->identity;
        return $this->render('info', ['user' => $user]);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchWithoutAdmin(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $query = Meter::find()->where(['user_id' => $id]);
        $dataProvider = new ActiveDataProvider(['query' => $query, 'pagination' => false]);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
        ]);
    }


    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new UserForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if ($id = UserService::createFromUserForm($form)) {

                return $this->redirect(['view', 'id' => $id]);
            }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $form = UserService::createUserFormById($id);;
        $form->scenario = UserForm::SCENARIO_UPDATE;

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if ($id = UserService::createFromUserForm($form)) {

                return $this->redirect(['view', 'id' => $id]);
            }
        }

        return $this->render('update', [
            'model' => $form,
        ]);
    }
}

modules/admin/views/user/_form.php
<?php

use app\helpers\AuthHelper;
use app\models\db\User;
use app\models\forms\UserForm;
use app\repositories\RailwayRepository;
use kartik\date\DatePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model UserForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'xcode')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'role')->dropDownList(AuthHelper::listRoles()) ?>

    <?= $form->field($model, 'egrpo')->textInput() ?>

    <?= $form->field($model, 'contract_number')->textInput() ?>

    <?= $form->field($model, 'contract_conclusion_date')->widget(DatePicker::className(),
        [
            'language' => 'ru',
            'removeButton' => false,
            'options' => ['autocomplete' => 'off'],
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ]
        ]
    ) ?>


    <?= $form->field($model, 'is_railway')->dropDownList($model->getIsRailwayList()) ?>

    <?= $form->field($model, 'railways')->checkboxList(RailwayRepository::getListIdTitle()) ?>

    <div class="panel panel-default">
        <div class="panel-heading"><h4><i class="glyphicon glyphicon-pencil"></i> Ответственные лица</h4></div>
        <div class="panel-body">
            <div class="container-items">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <?= $form->field($model, 'position1_full_name')->textInput() ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <?= $form->field($model, 'position2_full_name')->textInput() ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <?= $form->field($model, 'signatory')->dropDownList(User::getSignatoryList()) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\searches\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'xcode') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'deleted') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\User */

$this->title = 'Добавление пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/user/index.php
<?php

use app\models\db\User;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\searches\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить пользователя', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Название организации',
                'value' => function($model) {
                    /** @var User $model */

                    if ($model->is_railway) {
                        $titles = ArrayHelper::getColumn($model->railways, 'title');
                        $response = implode(',', $titles);
                    } else {
                        $response = $model->title;
                    }

                    return $response;
                }
            ],
            'xcode',
            'email',
            'egrpo',
            'created_at:datetime',
            'updated_at:datetime',
            [
                'attribute' => 'is_railway',
                'value' => function($model) {
                    /** @var User $model */
                    return $model->is_railway ? 'Да' : 'Нет';
                },
                'filter' => [1 => 'Да', 0 => 'Нет']
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}'
            ],
        ],
    ]); ?>
</div>

modules/admin/views/user/info.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user app\models\db\User */
/* @var $startDate string */
/* @var $meterList array */
/* @var $railwayList array */

$this->title = 'Пользователь: ' . $user->xcode;
$this->params['breadcrumbs'][] = 'Инфо';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= \yii\widgets\DetailView::widget([
        'model' => $user,
        'attributes' => [
            'xcode',
            'email',
            'created_at:datetime',
            'updated_at:datetime',

        ],
    ]) ?>

</div>

modules/admin/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\User */

$this->title = 'Редактирование пользователя: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/user/view.php
<?php

use app\models\db\User;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\YiiAsset;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\db\User */

$this->title = $model->xcode;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('К списку', ['index', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
    </p>

    <?= DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'xcode',
            'title',
            'email',
            'egrpo',
            'created_at:datetime',
            'updated_at:datetime',
            'position1_full_name',
            'position2_full_name',
            [
                'attribute'  => 'signatory',
                'value'  => function ($model) {
                    /** @var User $model */

                    return User::getSignatoryList()[$model->signatory];
                },
            ],
            'contract_number',
            'contract_conclusion_date:date',
            [
                'label'  => 'Телефоны',
                'format' => 'raw',
                'value'  => function ($model) {
                    /** @var User $model */

                    $phones = $model->phones;
                    $response = '';

                    foreach ($phones as $phone) {
                        $response .= $phone->comment . ' ' . $phone->number;
                    }

                    return $response;
                },
            ],
            [
                'label' => 'Ж/д',
                'value' => function ($model) {
                    /** @var User $model */

                    $titles = ArrayHelper::getColumn($model->railways, 'title');
                    $response = implode(',', $titles);

                    return $response;
                },
            ],
        ],
    ]) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'options' => [
            'style'=>'overflow: auto; word-wrap: break-word;'
        ],
        'columns'      => [
            ['class' => 'yii\grid\SerialColumn'],

            'zcode',
            [
                'attribute' => 'title',
                'format' => 'ntext',
            ],
            'address:ntext',

            [
                'class'    => 'yii\grid\ActionColumn',
                'contentOptions'=>['style'=>'width: 130px;'],
                'template' => '{current} {next} {table}',
                'buttons'  => [
                    'current' => function ($url, $model) {
                        return Html::a('Таблица(текущий месяц)', Url::to(['order/current-month', 'meter_id' => $model->id]), ['title' => 'Таблица(текущий месяц)', 'class' => 'btn btn-success']);
                    },
                    'next' => function ($url, $model) {
                        return Html::a('Таблица(следующий месяц)', Url::to(['order/next-month', 'meter_id' => $model->id]), ['title' => 'Таблица(следующий месяц)', 'class' => 'btn btn-info']);
                    },
                    'table' => function ($url, $model) {
                        return Html::a('Таблица(интервал)', Url::to(['order/table', 'meter_id' => $model->id, 'date_from' => date('Y-m'), 'date_to' => date('Y-m')]), ['title' => 'Таблица(интервал)', 'class' => 'btn btn-danger']);
                    },
                ],
            ],
        ],
    ]); ?>

</div>