controllers/FileController.php
<?php

namespace app\controllers;

use app\models\db\User;
use app\models\forms\OrderFileUploadForm;
use app\models\searches\FileSearch;
use app\services\FileService;
use app\services\FileUploaderService;
use app\services\OrderService;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;


class FileController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
        ini_set("memory_limit", "512M");
        set_time_limit(60);

        /** @var User $user */
        $user = Yii::$app->user->identity;

        $searchModel = new FileSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $user->id);

        $fileForm = new OrderFileUploadForm();

        $encodeInstance = UploadedFile::getInstance($fileForm, 'orderFileEncode');

        if ($encodeInstance) {
            $fileForm->orderFileEncode = $encodeInstance;

            $transaction = Yii::$app->db->beginTransaction();
            try {
                $orderFileDto = FileUploaderService::uploadOrderDocument($fileForm, $user);

                if ($orderFileDto) {
                    $file = FileService::createFromOrderFileUploadForm($orderFileDto, $user);
                    $userXlsFileData = FileService::parse($orderFileDto);
                    OrderService::confirm($userXlsFileData, $file);

                    Yii::$app->session->setFlash('success', 'Файл отправлен в обработку.');
                }

                $transaction->commit();
            } catch (\Throwable $throwable) {
                $transaction->rollBack();
                $encodeFileUrl = 'uploads/orders/' . $user->id . '/' . $fileForm->orderFileEncode->baseName . '.' . $fileForm->orderFileEncode->extension;

                if (file_exists($encodeFileUrl)) {
                    unlink($encodeFileUrl);
                }

                Yii::error($throwable->getMessage());
                Yii::$app->session->setFlash('danger', $throwable->getMessage());
            }
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'fileForm' => $fileForm,
        ]);
    }
}

controllers/ForecastController.php
<?php

namespace app\controllers;

use app\models\db\Meter;
use app\models\db\User;
use app\modules\weather\repositories\ForecastRepository;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\Response;

class ForecastController extends Controller
{

    public $forecastRepository;

    public function __construct($id, $module, ForecastRepository $forecastRepository)
    {
        parent::__construct($id, $module, []);

        $this->forecastRepository = $forecastRepository;
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['chart-by-meter-id'],
                        'allow' => true,
                        'roles' => [User::ROLE_USER, User::ROLE_ADMINISTRATOR],
                    ],
                ],
            ],
        ];
    }

    public function actionChartByMeterId()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $meterId = Yii::$app->request->post('meterId');
        $meter = Meter::findOne($meterId);

        if ($meter->city_id) {
            $forecasts = $this->forecastRepository->getByForeignId($meter->city_id);

            $categories = ArrayHelper::getColumn($forecasts->weatherForecasts, 'datetime');
            $minTemperaturePoints = ArrayHelper::getColumn($forecasts->weatherForecasts, 'temp_min');
            $maxTemperaturePoints = ArrayHelper::getColumn($forecasts->weatherForecasts, 'temp_max');

            $categories = str_replace('00:00', '00', $categories);

            foreach ($minTemperaturePoints as &$minTemperaturePoint) {
                $minTemperaturePoint = floor($minTemperaturePoint);
            }

            foreach ($maxTemperaturePoints as &$maxTemperaturePoint) {
                $maxTemperaturePoint = floor($maxTemperaturePoint);
            }

            return json_encode([
                'categories' => $categories,
                'maxTemperaturePoints' => $maxTemperaturePoints,
                'minTemperaturePoints' => $minTemperaturePoints
            ]);
        }

        return json_encode([]);
    }
}

controllers/OrderController.php
<?php

namespace app\controllers;

use app\dto\date\DateDto;
use app\dto\order\UserXlsDataRowDto;
use app\helpers\DateHelper;
use app\models\db\Meter;
use app\models\db\Order;
use app\models\db\User;
use app\models\forms\OrderForm;
use app\models\searches\OrderSearch;
use app\repositories\MeterRepository;
use app\repositories\OrderRepository;
use app\repositories\RailwayRepository;
use app\services\OrderService;
use PhpOffice\PhpSpreadsheet\Exception;
use PhpOffice\PhpSpreadsheet\Reader\Xls\Color\BIFF8;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use function GuzzleHttp\Psr7\str;


class OrderController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_USER],
                    ],
                    [
                        'allow' => ['print', 'all'],
                        'roles' => [User::ROLE_USER],
                    ],
                    [
                        'actions' => ['current-month', 'next-month', 'table'],
                        'allow' => true,
                        'roles' => [User::ROLE_USER, User::ROLE_ADMINISTRATOR],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, Yii::$app->user->getId());

        $user = Yii::$app->user->getIdentity();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'meterList' => MeterRepository::getListIdZcode($user),
        ]);
    }

    public function actionView($id)
    {
        if (Yii::$app->user->can('orderAccess', ['orderId' => $id])) {
            $order = OrderRepository::getById($id);
            return $this->render('view', [
                'model' => $order,
            ]);
        }
    }

    public function actionCreate()
    {
        $form = new OrderForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if ($id = OrderService::createFromOrderForm($form)) {
                return $this->redirect(['view', 'id' => $id]);
            }
        }

        $user = Yii::$app->user->identity;
        return $this->render('create', [
            'model' => $form,
            'startDate' => OrderService::getStartDate(),
            'meterList' => MeterRepository::getListIdZcode($user),
            'railwayList' => RailwayRepository::getListIdTitle($user),
        ]);
    }

    public function actionUpdate($id)
    {
        if (Yii::$app->user->can('orderAccess', ['orderId' => $id])) {
            $model = OrderRepository::getById($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            $user = Yii::$app->user->identity;
            return $this->render('update', [
                'model' => $model,
                'startDate' => OrderService::getStartDate(),
                'meterList' => MeterRepository::getListIdZcode($user),
                'railwayList' => RailwayRepository::getListIdTitle($user),
            ]);
        }
    }

    public function actionRenominate($id)
    {
        $model = OrderRepository::getById($id);

        $model->scenario = Order::SCENARIO_RENOMINATE;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('renominate', [
            'model' => $model,
        ]);
    }

    public function actionPrint()
    {
        $dateFrom = Yii::$app->request->post('date_from');
        $dateTo = Yii::$app->request->post('date_to');
        $meterId = Yii::$app->request->post('meter_id');

        if (strlen($dateFrom) == 7) {
            $dateFrom = $dateFrom . '-01';
            $daysInMonth = date('t', strtotime($dateTo . '-01'));
            $dateTo = $dateTo . '-' . $daysInMonth;
        }

        $data = OrderService::getUserXlsData($dateFrom, $dateTo, $meterId);

        $spreadsheet = new Spreadsheet();
        try {
            $sheet = $spreadsheet->getActiveSheet();

            $sheet->setCellValue('A' . 1, 'Дата');
            $sheet->setCellValue('B' . 1, 'Номинация, тыс. м3');
            $sheet->setCellValue('C' . 1, 'Реноминация, тыс. м3');
            $sheet->setCellValue('D' . 1, 'z - код');

            $rowNumber = 2;
            if ($data->rows) {
                foreach ($data->rows as $rowDto) {
                    $sheet->setCellValue('A' . $rowNumber, $rowDto->date);
                    $sheet->setCellValue('B' . $rowNumber, $rowDto->nomination);
                    $sheet->setCellValue('C' . $rowNumber, $rowDto->renomination);
                    $sheet->setCellValue('D' . $rowNumber, $rowDto->zcode);

                    $rowNumber++;
                }
            }

            $filename = $dateFrom . '-' . $dateTo . '.xls';
            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="' . $filename . '"');
            header('Cache-Control: max-age=0');

            $writer = new Xls($spreadsheet);
            $writer->save('php://output');
        } catch (Exception $e) {
            Yii::error($e->getMessage());
        }
    }

    public function actionCurrentMonth()
    {
        $meterId = Yii::$app->request->get('meter_id');
        /** @var User $user */
        $user = Yii::$app->user->getIdentity();
        $print = Yii::$app->request->post('print');

        if (!Meter::findOne(['id' => $meterId, 'user_id' => $user->id])) {
            throw new ForbiddenHttpException('NotFound', '403');
        }

        $date = DateHelper::getDates(DateHelper::CURRENT_MONTH);

        if (Yii::$app->request->isPost && !$print) {
            $nominations = Yii::$app->request->post('nomination', []);
            $renominations = Yii::$app->request->post('renomination', []);

            OrderService::saveNominations($nominations, $meterId, $date);
            OrderService::saveRenominations($renominations, $meterId, $date);

            Yii::$app->session->setFlash('success', 'Изменения сохранены.');
        }

        $this->layout = 'withoutBorder';

        $data = OrderService::getOrdersByDayAndSums($date, $meterId);

        if ($print) {
            $meter = Meter::findOne($meterId);
            $sum = Yii::$app->request->post('nomination') ? $data['sums']['nomination'] : $data['sums']['renomination'];

            $startDate = "1.$date->month.$date->year";
            $endDate = "{$data['daysInMonth']}.$date->month.$date->year";

            return $this->renderPartial('print-table',
                [
                    'dataByMonths' => [
                        [
                            'days' => range(1, $data['daysInMonth']),
                            'meter' => $meter,
                            'sum' => $sum,
                            'orderByDay' => $data['print']['days'],
                            'endDay' => $data['daysInMonth'],
                            'month' => $date->month,
                            'year' => $date->year,
                        ]
                    ],
                    'endDate' => $endDate,
                    'meter' => $meter,
                    'days' => range(1, $data['daysInMonth']),
                    'startDate' => $startDate
                ]
            );
        }

        return $this->render('table', [
            'date' => $date->month . '.' . $date->year,
            'days' => range(1, $data['daysInMonth']),
            'nominationSum' => $data['sums']['nomination'],
            'renominationSum' => $data['sums']['renomination'],
            'orders' => $data['days'],
        ]);
    }

    public function actionNextMonth()
    {
        $this->layout = 'withoutBorder';

        $meterId = Yii::$app->request->get('meter_id');
        $print = Yii::$app->request->post('print');

        /** @var User $user */
        $user = Yii::$app->user->getIdentity();

        if (!Meter::findOne(['id' => $meterId, 'user_id' => $user->id])) {
            throw new ForbiddenHttpException('NotFound', '403');
        }

        $date = DateHelper::getDates(DateHelper::NEXT_MONTH);

        if (Yii::$app->request->isPost && !$print) {
            $nominations = Yii::$app->request->post('nomination', []);
            $renominations = Yii::$app->request->post('renomination', []);

            OrderService::saveNominations($nominations, $meterId, $date);
            OrderService::saveRenominations($renominations, $meterId, $date);

            Yii::$app->session->setFlash('success', 'Изменения сохранены.');
        }

        $data = OrderService::getOrdersByDayAndSums($date, $meterId);

        if ($print) {
            $meter = Meter::findOne($meterId);
            $sum = Yii::$app->request->post('nomination') ? $data['sums']['nomination'] : $data['sums']['renomination'];

            $startDate = "1.$date->month.$date->year";
            $endDate = "{$data['daysInMonth']}.$date->month.$date->year";

            return $this->renderPartial('print-table',
                [
                    'dataByMonths' => [
                        [
                            'days' => range(1, $data['daysInMonth']),
                            'meter' => $meter,
                            'sum' => $sum,

views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */
/* @var $form yii\widgets\ActiveForm */
/* @var $startDate string */

/* @var $meterList array */
/* @var $railwayList array */

/* @var $categories array */
/* @var $minTemperaturePoints array */
/* @var $maxTemperaturePoints array */

?>
<div class="order-form">
    <div class="row">
        <?php $form = ActiveForm::begin(); ?>
        <div class="col-lg-6">
            <?= $form->field($model, 'id')->hiddenInput()->label(false) ?>

            <?= $form->field($model, 'meter')->dropDownList($meterList, ['class' => 'form-control meter', 'data-url' => \yii\helpers\Url::to('/forecast/chart-by-meter-id')]) ?>

            <?php if (!empty($railwayList)): ?>
                <?= $form->field($model, 'railway')->dropDownList($railwayList) ?>
            <?php endif; ?>

            <?= $form->field($model, 'nomination')->input('numeric') ?>

            <?= $form->field($model, 'date')->widget(\kartik\date\DatePicker::className(),
                [
                    'language' => 'ru',
                    'removeButton' => false,
                    'pluginOptions' => [
                        'todayHighlight' => true,
                        'startDate' => $startDate,
                        'format' => 'yyyy-mm-dd'
                    ]
                ]
            ) ?>

            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>

        </div>
        <div class="col-lg-6">
            <div id="weather-forecast-chart" class="weather-forecast-chart"></div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<?php
\app\assets\OrderAsset::register($this);
?>

views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\searches\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'meter_id') ?>

    <?= $form->field($model, 'nomination') ?>

    <?= $form->field($model, 'renomination') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'deleted') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */
/* @var $startDate string */
/* @var $meterList array */
/* @var $railwayList array */

$this->title = 'Создать заказ';
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'startDate' => $startDate,
        'railwayList' => $railwayList,
        'meterList' => $meterList,
    ]) ?>

</div>

views/order/index.php
<?php

use app\assets\OrderAsset;
use app\models\db\Order;
use app\services\OrderService;
use yii\grid\GridView;
use yii\helpers\Html;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $searchModel app\models\searches\OrderSearch */

/* @var $dataProvider yii\data\ActiveDataProvider */

use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */
/* @var $form yii\widgets\ActiveForm */
/* @var $startDate string */

/* @var $meterList array */
/* @var $railwayList array */

/* @var $categories array */
/* @var $minTemperaturePoints array */
/* @var $maxTemperaturePoints array */
$this->title = 'Погода';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="order-form">
        <div class="row">
            <div class="col-lg-12">
                <?= Html::dropDownList('meter', null, $meterList, [
                    'class' => 'form-control meter', 'data-url' => Url::to('/forecast/chart-by-meter-id')
                ]) ?>
            </div>
            <div class="col-lg-12">
                <div id="weather-forecast-chart" class="weather-forecast-chart"></div>
            </div>
        </div>
    </div>
    <?php
    OrderAsset::register($this);
    ?>
</div>

views/order/renominate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */

$this->title = 'Реноминация заказа: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Реноминация';
?>
<div class="order-renominate">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="order-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'id')->hiddenInput()->label(false) ?>

        <?= $form->field($model, 'meter_id')->dropDownList(\app\repositories\MeterRepository::getListIdZcode(Yii::$app->user->identity), ['disabled' => true]) ?>

        <?= $form->field($model, 'nomination')->input('numeric', ['disabled' => true]) ?>

        <?= $form->field($model, 'renomination')->input('numeric') ?>

        <?= $form->field($model, 'date')->widget(\kartik\date\DatePicker::className(),
            [
                'disabled' => true,
                'language' => 'ru',
                'removeButton' => false,
                'pluginOptions' => [
                    'todayHighlight' => true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]
        ) ?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/order/tables-all.php
<?php

use app\assets\OrderAllAsset;
use app\assets\TableAsset;
use app\helpers\DateHelper;
use app\services\OrderService;
use kartik\date\DatePicker;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataByMonth array */
/* @var $meterId integer */
/* @var $from string */
/* @var $to string */

$this->title = 'Заказ по месяцам';
$this->params['breadcrumbs'][] = $this->title;

TableAsset::register($this);
OrderAllAsset::register($this);
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::beginForm('', 'post', ['class' => 'form-all']) ?>

        <?= Html::hiddenInput('to_excel', 1, ['class' => 'to-excel']) ?>
    <div class="row">
        <div class="col-lg-2">
            <?= Html::dropDownList('date_from', null, DateHelper::getFeatureMonths(), ['class' => 'form-control']) ?>
        </div>
        <div class="col-lg-2">
            <?= Html::dropDownList('date_to', null, DateHelper::getFeatureMonths(), ['class' => 'form-control']) ?>
        </div>
        <div class="col-lg-1">
            <?= Html::button('В excel', ['class' => 'btn btn-success submit-excel']) ?>
        </div>
        <div class="col-lg-1">
            <?= Html::button('Применить', ['class' => 'btn btn-info submit-supply']) ?>
        </div>
        <div class="col-lg-1">
            <?= Html::a('Загрузки', '/file/index', ['class' => 'btn btn-primary to-upload hide']) ?>
        </div>
    </div>
    <?= Html::endForm() ?>
    </p>

    <?php foreach ($errors as $message): ?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <?= $message ?>
        </div>
    <?php endforeach; ?>

    <?= Html::beginForm('', 'post') ?>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <?php foreach ($dataByZcodeAndMonth as $zcode => $dataByMonth): ?>

            <div class="panel panel-default">
                <div class="panel-heading" role="tab" id="heading<?= $zcode ?>">
                    <h4 class="panel-title">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $zcode ?>"
                           aria-expanded="true" aria-controls="collapse<?= $zcode ?>">
                            Z-код: <?= $zcode ?>
                        </a>
                    </h4>
                </div>
                <div id="collapse<?= $zcode ?>" class="panel-collapse collapse" role="tabpanel"
                     aria-labelledby="heading<?= $zcode ?>">
                    <div class="panel-body">

                        <?php foreach ($dataByMonth as $date => $table): ?>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><?= $table['date'] ?></h3>
                                </div>
                                <div class="panel-body">
                                    <!--<p>
                                        <?= Html::a('Печать номинации',
                                        Url::current([], true), [
                                            'target' => '_blank',
                                            'class' => 'btn btn-info',
                                            'data-method' => 'POST',
                                            'data-params' => [
                                                'print' => true,
                                                'nomination' => true,
                                                'print_date' => $date,
                                                'csrf_param' => Yii::$app->request->csrfParam,
                                                'csrf_token' => Yii::$app->request->csrfToken,
                                            ],
                                        ]) ?>​
                                        <?= Html::a('Печать реноминации',
                                        Url::current([], true), [
                                            'target' => '_blank',
                                            'class' => 'btn btn-primary',
                                            'data-method' => 'POST',
                                            'data-params' => [
                                                'print' => true,
                                                'renomination' => true,
                                                'print_date' => $date,
                                                'csrf_param' => Yii::$app->request->csrfParam,
                                                'csrf_token' => Yii::$app->request->csrfToken,
                                            ],
                                        ]) ?>​
                                    </p>-->

                                    <h3>Номинация</h3>

                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Месяц</th>
                                            <th>Сумма</th>
                                            <?php foreach ($table['days'] as $day): ?>
                                                <th><?= $day ?></th>
                                            <?php endforeach; ?>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><?= $table['date'] ?></td>
                                            <td><?= $table['nominationSum'] ?></td>
                                            <?php foreach ($table['days'] as $day): ?>
                                                <td class="<?= date('w', strtotime($date . '-' . $day)) % 6 == 0 ? 'back-red' : '' ?>"><?= Html::textInput('data[' . $zcode . '][' . $date . '][' . $day . '][nomination]', $table['orders'][$day]->nomination ?? 0, [
                                                        'disabled' => !OrderService::canUpdateInTable($table['orders'][$day]),
                                                        'class' => 'width40'
                                                    ]) ?></td>
                                            <?php endforeach; ?>
                                        </tr>
                                        </tbody>
                                    </table>

                                    <h3>Реноминация</h3>

                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Месяц</th>
                                            <th>Сумма</th>
                                            <?php foreach ($table['days'] as $day): ?>
                                                <th><?= $day ?></th>
                                            <?php endforeach; ?>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td><?= $table['date'] ?></td>
                                            <td><?= $table['renominationSum'] ?></td>
                                            <?php foreach ($table['days'] as $day): ?>
                                                <td class="<?= date('w', strtotime($date . '-' . $day)) % 6 == 0 ? 'back-red' : '' ?>"><?= Html::textInput('data[' . $zcode . '][' . $date . '][' . $day . '][renomination]', (double)($table['orders'][$day]->renomination ?? $table['orders'][$day]->nomination ?? 0), [
                                                        'class' => 'width40',
                                                        'disabled' => !OrderService::canRenominateInTable($table['orders'][$day])
                                                    ]) ?></td>
                                            <?php endforeach; ?>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    <?= Html::endForm() ?>
</div>

views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */
/* @var $startDate string */
/* @var $meterList array */
/* @var $railwayList array */

$this->title = 'Редактирование заказа: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'startDate' => $startDate,
        'meterList' => $meterList,
        'railwayList' => $railwayList,
    ]) ?>

</div>