modules/admin/controllers/OrderController.php
<?php

namespace app\modules\admin\controllers;

use app\dto\date\DateDto;
use app\models\db\Meter;
use app\models\db\Order;
use app\models\db\Provider;
use app\models\db\Railway;
use app\models\db\User;
use app\modules\admin\models\searches\OrderSearch;
use app\services\OrderService;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_ADMINISTRATOR],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionListOrdersByProvider($providerId)
    {
        $query = Order::find()
            ->leftJoin(Meter::tableName(), 'meter_id=meter.id')
            ->where(['meter.provider_id' => $providerId]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $provider = Provider::findOne($providerId);

        return $this->render('list_orders_by_provider', ['dataProvider' => $dataProvider, 'provider' => $provider]);
    }

    public function actionListOrdersByRailway($railwayId)
    {
        $query = Order::find()->where(['railway_id' => $railwayId]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $railway = Railway::findOne($railwayId);

        return $this->render('list_orders_by_railway', ['dataProvider' => $dataProvider, 'railway' => $railway]);
    }

    public function actionPrint()
    {
        $dateFrom = Yii::$app->request->post('date_from');
        $dateTo = Yii::$app->request->post('date_to');
        $meterId = Yii::$app->request->post('meter_id');

        if (strlen($dateFrom) == 7) {
            $dateFrom = $dateFrom . '-01';
            $daysInMonth = date('t', strtotime($dateTo . '-01'));
            $dateTo = $dateTo . '-' . $daysInMonth;
        }

        $data = OrderService::getUserXlsData($dateFrom, $dateTo, $meterId);

        $spreadsheet = new Spreadsheet();
        try {
            $sheet = $spreadsheet->getActiveSheet();

            $sheet->setCellValue('A' . 1, 'Дата');
            $sheet->setCellValue('B' . 1, 'Номинация, тыс. м3');
            $sheet->setCellValue('C' . 1, 'Реноминация, тыс. м3');
            $sheet->setCellValue('D' . 1, 'z - код');

            $rowNumber = 2;
            if ($data->rows) {
                foreach ($data->rows as $rowDto) {
                    $sheet->setCellValue('A' . $rowNumber, $rowDto->date);
                    $sheet->setCellValue('B' . $rowNumber, $rowDto->nomination);
                    $sheet->setCellValue('C' . $rowNumber, $rowDto->renomination);
                    $sheet->setCellValue('D' . $rowNumber, $rowDto->zcode);

                    $rowNumber++;
                }
            }

            $filename = $dateFrom . '-' . $dateTo . '.xls';
            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="' . $filename . '"');
            header('Cache-Control: max-age=0');

            $writer = new Xls($spreadsheet);
            $writer->save('php://output');
        } catch (Exception $e) {
            Yii::error($e->getMessage());
        }
    }

    public function actionCurrentMonth()
    {
        $meterId = Yii::$app->request->get('meter_id');

        $this->layout = 'withoutBorder';

        $orders = Order::find()
            ->where(new Expression('MONTH(date) = MONTH(CURRENT_DATE()) AND YEAR(date) = YEAR(CURRENT_DATE())'))
            ->andWhere(['meter_id' => $meterId])
            ->orderBy('date')
            ->all();

        $nominationSum = 0;
        $renominationSum = 0;
        $ordersByDay = [];

        $days = date('t');
        foreach (range(1, $days) as $day) {
            $ordersByDay[$day] = date('Y-m-') . $day;
        }

        foreach ($orders as $order) {
            $nominationSum += $order->nomination;
            $renominationSum += (double)$order->renomination ?: $order->nomination;
            $ordersByDay[$order->getDay()] = $order;
        }

        $meter = Meter::findOne($meterId);
        if (Yii::$app->request->post('print')) {
            $sum = Yii::$app->request->post('nomination') ? $nominationSum : $renominationSum;
            foreach (range(1, date('t')) as $day) {
                $ordersByDay[$day] = 0;
            }
            foreach ($orders as $order) {
                $ordersByDay[$order->getDay()] = Yii::$app->request->post('nomination') ? $order->nomination ?: 0 : ((double)$order->renomination ?: $order->nomination ?: 0);
            }

            $startDate = "1." . date('m') . "." . date('Y');
            $endDate = $days . "." . date('m') . "." . date('Y');

            return $this->renderPartial('print-table',
                [
                    'dataByMonths' => [
                        'days'       => range(1, $days),
                        'meter'      => $meter,
                        'sum'        => $sum,
                        'orderByDay' => $ordersByDay,
                        'endDay'     => $days,
                        'month'      => date('m'),
                        'year'       => date('Y'),
                    ],
                    'endDate' => $endDate,
                    'startDate' => $startDate,
                    'days' => $days,
                    'meter' => $meter,
                ]
            );
        }

        return $this->render('table', [
            'meter'           => $meter,
            'date'            => date('m.Y'),
            'days'            => range(1, date('t')),
            'nominationSum'   => $nominationSum,
            'renominationSum' => $renominationSum,
            'orders'          => $ordersByDay,
        ]);
    }

    public function actionNextMonth()
    {
        $this->layout = 'withoutBorder';

        $meterId = Yii::$app->request->get('meter_id');
        /** @var User $user */

        $year = date('Y');
        $month = (string)date('m');
        if ($month == 12) {
            $month = '01';
            $year += 1;
        } else {
            $month += 1;
        }

        /** @var Order[] $orders */
        $orders = Order::find()
            ->where(new Expression('CAST(MONTH(date) AS UNSIGNED) = ' . $month . ' AND YEAR(date) = ' . $year))
            ->andWhere(['meter_id' => $meterId])
            ->orderBy('date')
            ->all();

        $nominationSum = 0;
        $renominationSum = 0;
        $ordersByDay = [];

        $days = date('t', strtotime("$year-$month-01"));
        foreach (range(1, $days) as $day) {
            $ordersByDay[$day] = "$year-$month-" . $day;
        }

        foreach ($orders as $order) {
            $nominationSum += $order->nomination;
            $renominationSum += (double)$order->renomination ?: $order->nomination;
            $ordersByDay[$order->getDay()] = $order;
        }

        $meter = Meter::findOne($meterId);
        if (Yii::$app->request->post('print')) {
            $sum = Yii::$app->request->post('nomination') ? $nominationSum : $renominationSum;
            foreach (range(1, $days) as $day) {
                $ordersByDay[$day] = 0;
            }

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\Meter;
use app\models\db\User;
use app\models\forms\UserForm;
use app\modules\admin\models\searches\UserSearch;
use app\services\UserService;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [User::ROLE_ADMINISTRATOR],
                    ],
                ],
            ],
        ];
    }


    public function actionInfo()
    {
        /** @var User $model */
        $user = \Yii::$app->user->identity;
        return $this->render('info', ['user' => $user]);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchWithoutAdmin(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $query = Meter::find()->where(['user_id' => $id]);
        $dataProvider = new ActiveDataProvider(['query' => $query, 'pagination' => false]);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
        ]);
    }


    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new UserForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if ($id = UserService::createFromUserForm($form)) {

                return $this->redirect(['view', 'id' => $id]);
            }
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $form = UserService::createUserFormById($id);;
        $form->scenario = UserForm::SCENARIO_UPDATE;

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if ($id = UserService::createFromUserForm($form)) {

                return $this->redirect(['view', 'id' => $id]);
            }
        }

        return $this->render('update', [
            'model' => $form,
        ]);
    }
}

modules/admin/views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'meter_id')->textInput() ?>

    <?= $form->field($model, 'nomination')->textInput() ?>

    <?= $form->field($model, 'renomination')->textInput() ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'deleted')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\searches\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'meter_id') ?>

    <?= $form->field($model, 'nomination') ?>

    <?= $form->field($model, 'renomination') ?>

    <?= $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'deleted') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/order/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */

$this->title = 'Create Order';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\searches\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заказы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions'=>function ($model, $key, $index, $grid){
            $class = empty($model->file_id) ? 'back-red' : '';
            return [
                'class'=>$class
            ];
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label' => 'X - код',
                'attribute' => 'xcode',
            ],
            [
                'label' => 'Z - код',
                'attribute' => 'zcode',
            ],
            'nomination',
            'renomination',
            'date',


            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{file}',
                'buttons' => [
                    'file' => function ($url, $model, $key) {
                        /** @var \app\models\db\Order $model */
                        $html = '';
                        if (!empty($model->file_id)) {
                            $html = Html::a('', '/' . $model->file->url . $model->file->file_name, ['title' => 'Файл', 'download' => true, 'class' => 'glyphicon glyphicon-download']);
                            $html .= Html::a('', '/' . $model->file->url . $model->file->file_name_encode, ['title' => 'Подписанный файл', 'download' => true, 'class' => 'glyphicon glyphicon-download']);
                        }
                        return $html;
                    }
                ]
            ],
        ],
    ]); ?>
</div>

modules/admin/views/order/list_orders_by_provider.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/** @var \app\models\db\Provider $provider */

$this->title = 'Заказы оператору ГТС/ГРМ ' . $provider->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="provider-list_orders_by_provider">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Счетчик',
                'value' => function($model){
                    /** @var \app\models\db\Order $model */
                    return $model->meter->title ;
                }
            ],
            'nomination',
            'renomination',
            'date',
        ],
    ]); ?>
</div>

modules/admin/views/order/list_orders_by_railway.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/** @var \app\models\db\Railway $railway */

$this->title = 'Заказы по ж/д ' . $railway->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="provider-list_orders_by_provider">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Счетчик',
                'value' => function($model){
                    /** @var \app\models\db\Order $model */
                    return $model->meter->title ;
                }
            ],
            'nomination',
            'renomination',
            'date',
        ],
    ]); ?>
</div>

modules/admin/views/order/table.php
<?php

use app\models\db\Meter;
use app\models\db\Order;
use app\services\OrderService;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $orders Order[] */
/* @var $meter Meter */
/* @var $nominationSum double */
/* @var $renominationSum double */
/* @var $days array */

$this->title = 'Заказ на месяц';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('К списку', ['user/view', 'id' => $meter->user->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Печать номинации',
            Url::current([], true), [
                'target'      => '_blank',
                'class'       => 'btn btn-info',
                'data-method' => 'POST',
                'data-params' => [
                    'print'      => true,
                    'nomination' => true,
                    'csrf_param' => Yii::$app->request->csrfParam,
                    'csrf_token' => Yii::$app->request->csrfToken,
                ],
            ]) ?>​
        <?= Html::a('Печать реноминации',
            Url::current([], true), [
                'target'      => '_blank',
                'class'       => 'btn btn-primary',
                'data-method' => 'POST',
                'data-params' => [
                    'print'        => true,
                    'renomination' => true,
                    'csrf_param'   => Yii::$app->request->csrfParam,
                    'csrf_token'   => Yii::$app->request->csrfToken,
                ],
            ]) ?>​
    </p>

    <h3>Номинация</h3>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Месяц</th>
            <th>Сумма</th>
            <?php foreach ($days as $day): ?>
                <th><?= $day ?></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><?= $date ?></td>
            <td><?= $nominationSum ?></td>
            <?php foreach ($days as $day): ?>
                <td class="width40"><?= $orders[$day]->nomination ?? 0 ?></td>
            <?php endforeach; ?>
        </tr>
        </tbody>
    </table>

    <h3>Реноминация</h3>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Месяц</th>
            <th>Сумма</th>
            <?php foreach ($days as $day): ?>
                <th><?= $day ?></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><?= $date ?></td>
            <td><?= $renominationSum ?></td>
            <?php foreach ($days as $day): ?>
                <td class="width40"><?=  $orders[$day]->renomination ?? $orders[$day]->nomination ?></td>
            <?php endforeach; ?>
        </tr>
        </tbody>
    </table>
</div>

modules/admin/views/order/tables.php
<?php

use app\helpers\DateHelper;
use app\modules\admin\assets\TableAsset;
use app\services\OrderService;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataByMonth array */
/* @var $meterId integer */
/* @var $from string */
/* @var $to string */

$this->title = 'Заказ по месяцам';
$this->params['breadcrumbs'][] = $this->title;

TableAsset::register($this);
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Html::beginForm('/admin/order/print', 'post', ['class' => 'table-form']) ?>
    <?= Html::hiddenInput('meter_id', $meterId) ?>
    <div class="row">
        <div class="col-sm-2">
            <?= Html::dropDownList('date_from', $from, DateHelper::getFeatureMonths(), ['class' => 'form-control date-from']) ?>
        </div>
        <div class="col-sm-2">
            <?= Html::dropDownList('date_to', $to, DateHelper::getFeatureMonths(), ['class' => 'form-control date-to']) ?>
        </div>
        <div class="col-sm-1">
            <?= Html::submitButton('Применить', ['class' => 'btn btn-success table-submit']) ?>
        </div>
        <div class="col-sm-1">
            <?= Html::button('В excel', ['class' => 'btn btn-info table-to-excel']) ?>
        </div>
        <div class="col-sm-1">
            <?= Html::button('Печать', ['class' => 'btn btn-primary table-print']) ?>
        </div>
    </div>
    <?= Html::endForm() ?>

    <br>
    <?= Html::beginForm('', 'post') ?>
    <?php foreach ($dataByMonth as $date => $table): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $table['date'] ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= Html::a('Печать номинации',
                        Url::current([], true), [
                            'target'      => '_blank',
                            'class'       => 'btn btn-info',
                            'data-method' => 'POST',
                            'data-params' => [
                                'print'      => true,
                                'nomination' => true,
                                'print_date' => $date,
                                'csrf_param' => Yii::$app->request->csrfParam,
                                'csrf_token' => Yii::$app->request->csrfToken,
                            ],
                        ]) ?>​
                    <?= Html::a('Печать реноминации',
                        Url::current([], true), [
                            'target'      => '_blank',
                            'class'       => 'btn btn-primary',
                            'data-method' => 'POST',
                            'data-params' => [
                                'print'        => true,
                                'renomination' => true,
                                'print_date'   => $date,
                                'csrf_param'   => Yii::$app->request->csrfParam,
                                'csrf_token'   => Yii::$app->request->csrfToken,
                            ],
                        ]) ?>​
                </p>

                <h3>Номинация</h3>

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Месяц</th>
                        <th>Сумма</th>
                        <?php foreach ($table['days'] as $day): ?>
                            <th><?= $day ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $table['date'] ?></td>
                        <td ><?= $table['nominationSum'] ?></td>
                        <?php foreach ($table['days'] as $day): ?>
                            <td class="<?= date('w', strtotime($date . '-' . $day)) % 6 == 0 ? 'back-red' : '' ?>"><?= Html::textInput('nomination[' . $date . '][' . $day . ']', isset($table['orders'][$day]) ? $table['orders'][$day]->nomination : 0, ['disabled' => !OrderService::canUpdateInTable($table['orders'][$day]), 'class' => 'width40']) ?></td>
                        <?php endforeach; ?>
                    </tr>
                    </tbody>
                </table>

                <h3>Реноминация</h3>

                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Месяц</th>
                        <th>Сумма</th>
                        <?php foreach ($table['days'] as $day): ?>
                            <th><?= $day ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $table['date'] ?></td>
                        <td><?= $table['renominationSum'] ?></td>
                        <?php foreach ($table['days'] as $day): ?>
                            <td class="<?= date('w', strtotime($date . '-' . $day)) % 6 == 0 ? 'back-red' : '' ?>"><?= Html::textInput('renomination[' . $date . '][' . $day . ']', empty((double)$table['orders'][$day]->renomination) ? $table['orders'][$day]->nomination : $table['orders'][$day]->renomination, ['class' => 'width40', 'disabled' => !OrderService::canRenominateInTable($table['orders'][$day])]) ?></td>
                        <?php endforeach; ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endforeach; ?>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    <?= Html::endForm() ?>
</div>

modules/admin/views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */

$this->title = 'Update Order: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\db\Order */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'meter_id',
            'nomination',
            'renomination',
            'date',
            'deleted',
        ],
    ]) ?>

</div>